global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 1s # Evaluate rules

scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  static_configs:
  - targets:
    - host.docker.internal:8080
